// quizmaker.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <iostream>
#include <fstream>
#include <string>
#include <conio.h> // getch

int main()
{
	std::cout << "QUIZZY quiz maker 9000" << std::endl;
	std::cout << "enter file's name to make: ";
	std::string filename;
	std::cin >> filename;

	std::ofstream file(filename, std::ofstream::trunc);

	file << "quiz:\n";
	file << "# auto generated by quizmaker\n";

	char input;
	std::string sinput;

	for (;;)
	{
		main:
		std::cout << "new (q)uestion or (f)inished?" << std::endl;
		input = getch();

		switch (input)
		{
		case 'f': // FINISHED
			goto neiltheend;
			break;

		case 'q': // QUESTION

			std::cout << "enter question: ";
			std::cin >> sinput;
			file << "question:\n" << sinput << "\n";

			for (;;)
			{
				std::cout << "new (c)orrect answer or (w)rong answer or (d)one?" << std::endl;
				input = getch();
				switch (input)
				{
				case 'c': // CORRECT ANSWER
					std::cout << "enter CORECT answer: ";
					std::cin >> sinput;
					file << "correct:\n" << sinput << "\n";
					break;
				case 'w': // WRONG ANSWER
					std::cout << "enter WRONGE answer: ";
					std::cin >> sinput;
					file << "wrong:\n" << sinput << "\n";
					break;
				case 'd': // DONE
					file << "questionend:\n\n";
					goto main; // go back to asking for questions
					break;
				}
			}
				
		}
	}

	neiltheend:

	file << "\n\nquizend:\n";

	file.close();

    return 0;
}

